name: Keep Render Alive

on:
  schedule:
    # Run every 10 minutes
    - cron: "*/10 * * * *"
  workflow_dispatch: # allows manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render service
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://urlshortener-vk07.onrender.com/active
